// Bait recommendation seed data for species
import Foundation

enum BaitSeedData {
    struct BaitEntry: Codable {
        let speciesId: Int64
        let baits: [String]
        let notes: String?
    }

    static let entries: [BaitEntry] = [
        // Freshwater Bass
        BaitEntry(speciesId: 1, baits: ["plastic worm","crankbait","spinnerbait","jig","topwater frog","swimbait","Texas-rigged soft plastic"], notes: "Topwater at dawn/dusk. Slow-roll spinnerbaits along weed edges. Texas rig in heavy cover."),
        BaitEntry(speciesId: 2, baits: ["tube jig","ned rig","drop shot","crankbait","jerkbait","live crayfish"], notes: "Smallmouth love crayfish patterns. Fish rocky structure with finesse presentations."),
        BaitEntry(speciesId: 3, baits: ["drop shot","shaky head","small crankbait","jerkbait","spinnerbait"], notes: "Target suspended fish with drop shot. Work rocky bluffs and current breaks."),
        // Panfish
        BaitEntry(speciesId: 4, baits: ["small jig","minnow","tube bait","micro crankbait","slip bobber with minnow"], notes: "Slow presentations near brush piles. Best during pre-spawn when crappie school up."),
        BaitEntry(speciesId: 5, baits: ["minnow","small jig","curly tail grub","road runner jig"], notes: "Spider rig with multiple jigs over submerged timber. Night fishing near lights."),
        BaitEntry(speciesId: 6, baits: ["worm","cricket","small jig","bread","corn","fly popper"], notes: "Small hooks, light line. Fly fishing with poppers is incredibly effective."),
        BaitEntry(speciesId: 7, baits: ["worm","small jig","cricket","waxworm"], notes: "Ultra-light tackle. Fish shallow weedy areas."),
        // Walleye/Perch
        BaitEntry(speciesId: 8, baits: ["jig and minnow","crankbait","live bait rig","blade bait","jigging spoon"], notes: "Walleye are light-sensitive — fish dawn, dusk, and cloudy days. Drift with bottom bouncers."),
        BaitEntry(speciesId: 9, baits: ["jig and minnow","blade bait","jigging spoon"], notes: "Similar to walleye tactics. Focus on deeper water and river current."),
        BaitEntry(speciesId: 10, baits: ["minnow","jig","worm","small spoon"], notes: "Schools travel together. Once you find one, keep fishing that spot."),
        // Pike/Musky
        BaitEntry(speciesId: 11, baits: ["spoon","spinnerbait","large jerkbait","live sucker","topwater buzzbait"], notes: "Use wire leader — pike have sharp teeth. Cast parallel to weed edges."),
        BaitEntry(speciesId: 12, baits: ["large bucktail","jerkbait","glide bait","topwater","live sucker"], notes: "Fish of 10,000 casts. Figure-8 at the boat on every cast."),
        // Catfish
        BaitEntry(speciesId: 13, baits: ["chicken liver","cut bait","stink bait","nightcrawler","punch bait","dip bait"], notes: "Fish on bottom near current breaks. Catfish feed most actively at night."),
        BaitEntry(speciesId: 14, baits: ["live bluegill","live perch","live shad","cut bait"], notes: "Flatheads prefer live bait. Fish log jams and deep holes at night."),
        BaitEntry(speciesId: 15, baits: ["cut shad","skipjack herring","live bait","chicken liver"], notes: "Blues are found in current. Fish channel edges and river bends."),
        BaitEntry(speciesId: 16, baits: ["nightcrawler","stink bait","chicken liver"], notes: "Bottom feeders. Fish at night in shallow muddy areas."),
        // Trout
        BaitEntry(speciesId: 17, baits: ["PowerBait","small spinner","fly nymph","fly dry","worm","salmon eggs"], notes: "Match the hatch when fly fishing. Use light line (2-4lb) in clear water."),
        BaitEntry(speciesId: 18, baits: ["spinner","streamer fly","rapala","live minnow","nightcrawler"], notes: "Brown trout are nocturnal. Trophy fish are caught on large streamers after dark."),
        BaitEntry(speciesId: 19, baits: ["small spinner","dry fly","worm","small spoon"], notes: "Brookies are found in cold mountain streams. Approach quietly — they spook easily."),
        BaitEntry(speciesId: 20, baits: ["jigging spoon","large spoon","trolling with downrigger","live bait"], notes: "Deep-water fish. Troll or jig deep — 60-100ft in summer."),
        // Salmon
        BaitEntry(speciesId: 21, baits: ["herring","spoon","spinner","fly streamer","roe"], notes: "Troll in open water. During runs, anchor or drift with roe."),
        BaitEntry(speciesId: 22, baits: ["spoon","spinner","fly","herring"], notes: "Aggressive biters. Cast spoons into schools for explosive strikes."),
        BaitEntry(speciesId: 23, baits: ["fly","spinner","spoon","roe"], notes: "During river runs, drift roe under a float. Match fly size to local patterns."),
        BaitEntry(speciesId: 24, baits: ["small spinner","spoon","fly","roe"], notes: "Pink salmon hit small pink or chartreuse lures aggressively during runs."),
        BaitEntry(speciesId: 25, baits: ["fly","small spoon","spinner","worm"], notes: "Arctic char respond well to bright-colored lures in cold, clear water."),
        // Striped/White Bass
        BaitEntry(speciesId: 26, baits: ["live eel","bucktail jig","plug","live bunker","topwater popper"], notes: "Stripers chase baitfish schools. Look for surface feeding blitzes."),
        BaitEntry(speciesId: 27, baits: ["small jig","spinner","crankbait","live minnow"], notes: "White bass school up aggressively. Match the size of the shad they're chasing."),
        // Misc Freshwater
        BaitEntry(speciesId: 28, baits: ["nightcrawler","crayfish","jig","crankbait"], notes: "Freshwater drum hit hard on the bottom. Found near current on rocky substrate."),
        BaitEntry(speciesId: 29, baits: ["topwater frog","spinnerbait","cut bait","soft plastic"], notes: "Bowfin are aggressive ambush predators. Fish weedy backwaters."),
        BaitEntry(speciesId: 30, baits: ["cut bait","live minnow","topwater","rope lure"], notes: "Gar have hard bony mouths — rope lures tangle in their teeth."),
        BaitEntry(speciesId: 31, baits: ["cut bait","live carp","rope lure","topwater"], notes: "Use heavy tackle and rope lures. Target shallow flats in spring."),
        // European Freshwater
        BaitEntry(speciesId: 32, baits: ["jig and minnow","soft plastic","crankbait","live bait"], notes: "Zander prefer slow presentations on the bottom. Fish deep during day, shallow at night."),
        BaitEntry(speciesId: 33, baits: ["large lure","live bait","dead bait","soft plastic swim bait"], notes: "Wels catfish grow enormous. Use strong tackle and large baits near deep holes."),
        BaitEntry(speciesId: 34, baits: ["boilie","corn","bread","dough bait","worm","pellet"], notes: "Carp respond to pre-baiting. Hair rig with boilies is the classic European method."),
        BaitEntry(speciesId: 35, baits: ["worm","bread","small jig","maggot","corn"], notes: "Tench love muddy-bottomed lakes with weed. Fish early morning on the bottom."),
        BaitEntry(speciesId: 36, baits: ["maggot","bread","worm","small spinner"], notes: "Roach are delicate biters. Use fine tackle and small hooks."),
        BaitEntry(speciesId: 37, baits: ["worm","bread","corn","maggot","feeder rig"], notes: "Bream school in deep water. Use a feeder rig with groundbait."),
        BaitEntry(speciesId: 38, baits: ["bread","worm","small spinner","fly"], notes: "Ide take bread on the surface. Good sport on light fly tackle."),
        BaitEntry(speciesId: 39, baits: ["dry fly","nymph","small spinner","worm"], notes: "Grayling have a delicate rise. Best on dry flies in clear rivers."),
        BaitEntry(speciesId: 40, baits: ["large streamer","spinner","live fish"], notes: "Huchen are the largest European salmonid. Cast large streamers in fast rivers."),
        BaitEntry(speciesId: 41, baits: ["hemp seed","maggot","pellet","boilie","meat"], notes: "Barbel fight hard in current. Use a rolling leger rig with luncheon meat."),
        BaitEntry(speciesId: 42, baits: ["spinner","crankbait","fly","live bait"], notes: "Asp are predatory cyprinids. Cast spinners at surface-feeding fish."),
        // African Freshwater
        BaitEntry(speciesId: 43, baits: ["live bait","lure","spinner","fly"], notes: "Nile perch grow massive. Troll with large lures in deep water."),
        BaitEntry(speciesId: 44, baits: ["chicken innards","worm","cut bait","dough bait"], notes: "African catfish feed on anything. Fish at night near shallow muddy areas."),
        BaitEntry(speciesId: 45, baits: ["bread","corn","worm","dough bait","fly"], notes: "Tilapia are herbivorous. Use small hooks with bread or corn on the bottom."),
        BaitEntry(speciesId: 46, baits: ["spinner","spoon","fly","live bait"], notes: "Tigerfish have razor-sharp teeth — use wire trace. Fast, aggressive retrieve."),
        // Tropical Freshwater
        BaitEntry(speciesId: 47, baits: ["topwater plug","jerkbait","spinnerbait","live shiner","fly popper"], notes: "Peacock bass are explosive surface strikers. Work topwater aggressively."),
        BaitEntry(speciesId: 48, baits: ["live bait","large plug","fly","cut bait"], notes: "Arapaima are air-breathers. Cast when they surface to gulp air."),
        BaitEntry(speciesId: 49, baits: ["spinner","spoon","fly streamer","live bait"], notes: "Dorado are acrobatic fighters. Fast retrieve with flashy lures."),
        BaitEntry(speciesId: 50, baits: ["topwater frog","live bait","soft plastic","spinnerbait"], notes: "Snakehead are ambush predators in thick cover. Topwater frogs are deadly."),
        BaitEntry(speciesId: 51, baits: ["spinner","spoon","fly","dough bait","live bait"], notes: "Mahseer live in fast Himalayan rivers. Use heavy tackle in strong current."),
        BaitEntry(speciesId: 52, baits: ["spinnerbait","large soft plastic","live bait","surface lure"], notes: "Murray cod ambush from structure. Cast tight to submerged logs."),
        BaitEntry(speciesId: 53, baits: ["worm","yabby","small lure","bait jig"], notes: "Silver perch school up in river bends. Use light tackle with natural baits."),
        // Brackish Predators
        BaitEntry(speciesId: 54, baits: ["live mullet","soft plastic","popper","fly","hard body lure"], notes: "Barramundi ambush from structure. Target snags and rock bars on tide changes."),
        BaitEntry(speciesId: 55, baits: ["live pilchard","soft plastic jig","topwater plug","fly"], notes: "Snook stage around structure on outgoing tides. Fish bridge pilings and mangroves."),
        BaitEntry(speciesId: 56, baits: ["live crab","live mullet","fly","soft plastic","cut bait"], notes: "Tarpon are the silver king. Set the hook hard — their mouths are bony."),
        BaitEntry(speciesId: 57, baits: ["shrimp fly","gotcha plug","crab pattern","small jig"], notes: "Bonefish feed on tidal flats. Sight-cast with precision — they spook easily."),
        BaitEntry(speciesId: 58, baits: ["live shrimp","cut mullet","gold spoon","soft plastic","fly"], notes: "Red drum tail in shallow grass. Sight-fish or cast gold spoons on flats."),
        BaitEntry(speciesId: 59, baits: ["live shrimp","soft plastic","topwater","popping cork","fly"], notes: "Spotted seatrout love popping corks with shrimp. Fish grass flats on incoming tide."),
        BaitEntry(speciesId: 60, baits: ["live minnow","bucktail jig","soft plastic grub","mud minnow"], notes: "Flounder lie flat on sandy bottom. Drag baits slowly along the bottom."),
        BaitEntry(speciesId: 61, baits: ["shrimp","crab","clam","cut bait","sand flea"], notes: "Black drum have crushers for teeth. Fish on bottom with natural baits near jetties."),
        BaitEntry(speciesId: 62, baits: ["live eel","jig","live crab","cut bait"], notes: "Cobia follow rays and sharks. Sight-cast jigs when you spot them cruising."),
        BaitEntry(speciesId: 63, baits: ["live crab","shrimp fly","small jig","crab pattern fly"], notes: "Permit are notoriously spooky. Delicate presentations of crab flies on flats."),
        BaitEntry(speciesId: 64, baits: ["topwater popper","jig","live bait","fly popper"], notes: "Jacks are brutally strong. Use heavy tackle — they'll head straight for structure."),
        // Snapper & Grouper
        BaitEntry(speciesId: 65, baits: ["live bait","cut squid","jig","butterfly jig"], notes: "Red snapper live over structure and reefs. Vertical jig or drop live bait."),
        BaitEntry(speciesId: 66, baits: ["live shrimp","cut bait","jig","soft plastic"], notes: "Mangrove snapper are wary. Use light leader and live shrimp around structure."),
        BaitEntry(speciesId: 67, baits: ["live pinfish","cut bait","jig","soft plastic"], notes: "Red grouper hold near bottom structure. Use enough weight to get down fast."),
        BaitEntry(speciesId: 68, baits: ["live bait","jig","trolling plug","soft plastic"], notes: "Gag grouper are aggressive. Fish reef edges and wrecks with heavy tackle."),
        BaitEntry(speciesId: 69, baits: ["live mullet","large jig","cut bait"], notes: "Goliath grouper are protected in many areas. Check local regulations."),
        // Mackerel/Pelagics
        BaitEntry(speciesId: 70, baits: ["live bait","trolling spoon","diving plug","wire rig"], notes: "King mackerel have sharp teeth. Use wire leader and troll along reef edges."),
        BaitEntry(speciesId: 71, baits: ["casting spoon","jig","live shrimp","Gotcha plug"], notes: "Spanish mackerel are fast. Use long-shank hooks or wire to prevent bite-offs."),
        BaitEntry(speciesId: 72, baits: ["metal jig","topwater popper","live bait","cut bait","fly"], notes: "Bluefish feed in frenzies. Use wire leader — they cut through mono easily."),
        BaitEntry(speciesId: 73, baits: ["fiddler crab","shrimp","sand flea","barnacle"], notes: "Sheepshead pick at crustaceans on pilings. Use small hooks — they're bait stealers."),
        BaitEntry(speciesId: 74, baits: ["small shrimp","cut bait","small jig"], notes: "Pinfish are common baitfish but fun on ultralight. Use tiny hooks."),
        // Tuna
        BaitEntry(speciesId: 75, baits: ["trolling lure","live bait","popper","jig","fly"], notes: "Yellowfin tuna are powerful. Troll skirted lures or cast poppers to feeding fish."),
        BaitEntry(speciesId: 76, baits: ["trolling lure","live bait","squid","butterfly jig"], notes: "Bluefin tuna are the ultimate prize. Match bait size to what they're eating."),
        BaitEntry(speciesId: 77, baits: ["trolling feather","small jig","live bait"], notes: "Albacore school in open water. Troll feathered jigs at speed."),
        BaitEntry(speciesId: 78, baits: ["trolling lure","live bait","feathered jig"], notes: "Skipjack are aggressive feeders. Light trolling gear works well."),
        BaitEntry(speciesId: 79, baits: ["squid","trolling lure","deep jig","live bait"], notes: "Bigeye tuna feed deep. Drop jigs to 200+ feet or night drift with squid."),
        BaitEntry(speciesId: 80, baits: ["trolling lure","live bait","fly","casting plug"], notes: "Mahi-mahi love weed lines and debris. Cast to floating structure."),
        // Billfish
        BaitEntry(speciesId: 81, baits: ["trolling lure","live bait","teaser and fly","ballyhoo"], notes: "Sailfish are spectacular on fly. Tease to the boat then pitch the fly."),
        BaitEntry(speciesId: 82, baits: ["trolling lure","live bait","skirted ballyhoo"], notes: "Blue marlin are the pinnacle of big game. Troll large skirted lures."),
        BaitEntry(speciesId: 83, baits: ["trolling lure","ballyhoo","live bait"], notes: "White marlin are acrobatic. Lighter tackle than blue marlin."),
        BaitEntry(speciesId: 84, baits: ["squid","trolling lure","deep bait"], notes: "Swordfish are deep dwellers. Night drift with lights and squid bait."),
        BaitEntry(speciesId: 85, baits: ["high-speed trolling lure","live bait","skirted lure"], notes: "Wahoo are the fastest fish. High-speed troll with heavy wire."),
        // Tropical Marine
        BaitEntry(speciesId: 86, baits: ["large popper","stickbait","fly","live bait"], notes: "GT are the ultimate sport fish. Cast big poppers to reef edges and channels."),
        BaitEntry(speciesId: 87, baits: ["jig","live bait","trolling plug","butterfly jig"], notes: "Amberjack are reef donkeys. Heavy vertical jigging over wrecks and reefs."),
        BaitEntry(speciesId: 88, baits: ["jig","live bait","trolling lure","soft plastic"], notes: "Yellowtail kingfish are powerful. Jig around offshore structures."),
        BaitEntry(speciesId: 89, baits: ["trolling lure","jig","live bait"], notes: "Rainbow runners are fast pelagics. Troll small lures at speed."),
        BaitEntry(speciesId: 90, baits: ["jig","live bait","trolling lure"], notes: "Deep reef fish. Vertical jig or drop live bait to structure."),
        BaitEntry(speciesId: 91, baits: ["jig","live bait","soft plastic","cut bait"], notes: "Spangled emperor frequent sandy patches near reef. Bottom fish with bait."),
        BaitEntry(speciesId: 92, baits: ["soft plastic","jig","live bait","trolling lure"], notes: "Coral trout ambush from reef. Cast soft plastics tight to coral bomies."),
        BaitEntry(speciesId: 93, baits: ["large jig","live bait","cut bait"], notes: "Giant grouper live in caves and wrecks. Use extremely heavy tackle."),
        BaitEntry(speciesId: 94, baits: ["soft plastic","jig","live bait","pilchard"], notes: "Snapper respond to berley. Fish on the bottom with flasher rigs."),
        // European Marine
        BaitEntry(speciesId: 95, baits: ["soft plastic","plug","fly","live sandeel","ragworm"], notes: "European bass hunt around rocky structure. Cast lures on high tide."),
        BaitEntry(speciesId: 96, baits: ["jig","live bait","pirk","shad"], notes: "Cod are deep-water bottom feeders. Use heavy jigs or pirks over wrecks."),
        BaitEntry(speciesId: 97, baits: ["soft plastic","spinner","fly","live sandeel"], notes: "Pollack hunt mid-water around wrecks. Work lures on the drop."),
        BaitEntry(speciesId: 98, baits: ["jig","worm","squid strip","pirk"], notes: "Haddock are bottom feeders. Fish with baited hooks over rough ground."),
        BaitEntry(speciesId: 99, baits: ["live bait","squid","cut bait","jig"], notes: "Turbot lie on sandy ground. Drift with live bait on the bottom."),
        BaitEntry(speciesId: 100, baits: ["fly","spinner","spoon","worm","roe"], notes: "Atlantic salmon are the king of game fish. Fly fishing is traditional."),
        BaitEntry(speciesId: 101, baits: ["bread","shrimp","worm","small jig","fly"], notes: "Gilthead seabream are powerful fighters. Light tackle with natural baits."),
        BaitEntry(speciesId: 102, baits: ["live bait","jig","soft plastic","trolling"], notes: "Common dentex are aggressive reef predators. Vertical jig over structure."),
        // Sharks
        BaitEntry(speciesId: 103, baits: ["live bait","cut bait","chunk bait"], notes: "Bull sharks are found in rivers and estuaries. Heavy tackle mandatory."),
        BaitEntry(speciesId: 104, baits: ["live bait","cut bait","topwater plug"], notes: "Blacktip sharks are acrobatic. Common from shore and piers."),
        BaitEntry(speciesId: 105, baits: ["large live bait","large cut bait"], notes: "Tiger sharks require extremely heavy tackle. Night fishing is productive."),
        BaitEntry(speciesId: 106, baits: ["large live bait","chunk bait","tuna head"], notes: "Great whites are protected in most areas. Check local regulations."),
        BaitEntry(speciesId: 107, baits: ["live bait","trolling lure","chunk bait"], notes: "Mako sharks are fast and leap. One of the best shark species to target."),
        BaitEntry(speciesId: 108, baits: ["cut bait","squid","mackerel chunk"], notes: "Blue sharks are common offshore. Chum heavily to attract them."),
        BaitEntry(speciesId: 109, baits: ["live bait","large cut bait"], notes: "Hammerheads are strong fighters. Target from shore or boat with heavy gear."),
        BaitEntry(speciesId: 110, baits: ["cut bait","shrimp","crab"], notes: "Stingrays are not typically targeted but caught incidentally on cut bait."),
        // Flatfish
        BaitEntry(speciesId: 111, baits: ["bucktail jig","live minnow","strip bait","soft plastic"], notes: "Summer flounder are active predators. Drift or slow troll with jigs."),
        BaitEntry(speciesId: 112, baits: ["large jig","cut bait","herring","circle hook rig"], notes: "Atlantic halibut are massive. Fish deep with large baits on heavy gear."),
        BaitEntry(speciesId: 113, baits: ["herring","jig","cut bait","octopus"], notes: "Pacific halibut fishing is a deep-water pursuit. Drift with large herring."),
        // More Marine
        BaitEntry(speciesId: 114, baits: ["trolling lure","live bait","metal slug"], notes: "Narrow-barred Spanish mackerel hit high-speed trolled lures."),
        BaitEntry(speciesId: 115, baits: ["topwater plug","jig","live bait","tube lure"], notes: "Barracuda are lightning fast. Use wire trace and flashy lures."),
        BaitEntry(speciesId: 116, baits: ["popper","jig","fly","live bait"], notes: "Bigeye trevally school around FADs and reef edges."),
        BaitEntry(speciesId: 117, baits: ["jig","soft plastic","live bait"], notes: "Golden trevally follow large marine animals. Cast when spotted."),
        BaitEntry(speciesId: 118, baits: ["bread","fly","dough bait","small jig"], notes: "Milkfish are herbivorous. Fly fishing with bread-fly patterns is the method."),
        BaitEntry(speciesId: 119, baits: ["small jig","fly","live shrimp","spoon"], notes: "Ladyfish are acrobatic and fun on light tackle. Cast to schools."),
        // South African Marine
        BaitEntry(speciesId: 120, baits: ["live mullet","sardine","squid","soft plastic","jig"], notes: "Dusky kob are prized SA fish. Fish estuaries and surf with live bait."),
        BaitEntry(speciesId: 121, baits: ["live bait","spoon","fly","plug"], notes: "Leervis are fast predators in the surf zone. Cast lures into white water."),
        BaitEntry(speciesId: 122, baits: ["red bait","white mussel","sardine","wonder worm"], notes: "Galjoen is South Africa's national fish. Surf fishing with red bait is traditional."),
        BaitEntry(speciesId: 123, baits: ["squid","red bait","chokka","jig"], notes: "Red roman are found on rocky reefs. Drop bait or jig near the bottom."),
        BaitEntry(speciesId: 124, baits: ["sardine","bread","white mussel","shrimp"], notes: "Blacktail are common rocky shore fish. Light tackle with small baits."),
        BaitEntry(speciesId: 125, baits: ["bread","red bait","wonder worm"], notes: "Strepie school in the surf. Use small hooks and bread."),
        BaitEntry(speciesId: 126, baits: ["prawn","worm","bread","small crab"], notes: "Cape stumpnose are estuary fish. Light tackle with prawns works well."),
        BaitEntry(speciesId: 127, baits: ["sand prawn","white mussel","wonder worm","crab"], notes: "White steenbras run along beaches. Surf fish with natural baits."),
        BaitEntry(speciesId: 128, baits: ["live bait","squid","jig","sardine"], notes: "Red steenbras are prized reef fish. Heavy tackle on deep reefs."),
        BaitEntry(speciesId: 129, baits: ["squid","sardine","jig"], notes: "Seventy-four are beautiful but critically endangered. Handle with extreme care."),
        BaitEntry(speciesId: 130, baits: ["sardine","trolling lure","feathered jig","spoon"], notes: "Snoek are the Cape's iconic fish. Troll or handline with shiny lures."),
        // Grouper
        BaitEntry(speciesId: 131, baits: ["live bait","jig","cut bait","soft plastic"], notes: "Dusky grouper hide in caves. Drop bait near rocky structure."),
        BaitEntry(speciesId: 132, baits: ["live bait","jig","soft plastic","trolling plug"], notes: "Black grouper are powerful. Fish reef edges with heavy tackle."),
        BaitEntry(speciesId: 133, baits: ["squid strip","clam","jig","cut bait"], notes: "Black sea bass love wrecks and artificial reefs. Drop and jig."),
        BaitEntry(speciesId: 134, baits: ["clam","squid","worm","small jig"], notes: "Scup are easy to catch. Bottom fish over hard structure."),
        BaitEntry(speciesId: 135, baits: ["green crab","jig","clam","Asian crab"], notes: "Tautog love crabs. Fish tight to structure with a jig tipped with crab."),
        BaitEntry(speciesId: 136, baits: ["bread","corn","small jig","fly"], notes: "Mullet are vegetarian. Use bread on small hooks or match-the-hatch flies."),
        BaitEntry(speciesId: 137, baits: ["sand flea","shrimp","bloodworm","cut bait"], notes: "Kingfish feed in the surf. Fish on the bottom with natural baits."),
        BaitEntry(speciesId: 138, baits: ["bloodworm","shrimp","cut bait","small jig"], notes: "Spot croaker are excellent bait and table fare. Small hooks on bottom."),
        BaitEntry(speciesId: 139, baits: ["shrimp","squid","bloodworm","cut bait"], notes: "Atlantic croaker are the most caught fish in the Chesapeake Bay."),
        BaitEntry(speciesId: 140, baits: ["sand flea","shrimp","jig","small crab"], notes: "Pompano are prized for their taste. Surf fish with sand fleas."),
        BaitEntry(speciesId: 141, baits: ["live shrimp","jig","cut bait","fly"], notes: "Tripletail float near surface structure. Sight-cast when spotted."),
        BaitEntry(speciesId: 142, baits: ["small jig","cut bait","shrimp"], notes: "Lionfish are invasive and delicious. Spear or jig near reefs."),
        BaitEntry(speciesId: 143, baits: ["jig","shrimp fly","small soft plastic"], notes: "Blue rockfish school over rocky reefs. Light jigging is effective."),
        BaitEntry(speciesId: 144, baits: ["large jig","live bait","soft plastic swim bait"], notes: "Lingcod are aggressive ambush predators. Jig aggressively over rocky bottom."),
        BaitEntry(speciesId: 145, baits: ["jig","cut bait","herring","squid"], notes: "Sablefish live deep. Fish with heavy jigs in 200-1000m of water."),
        BaitEntry(speciesId: 146, baits: ["live bait","fly","jig","soft plastic"], notes: "Sheephead live around kelp forests. Target with live bait near the bottom."),
        BaitEntry(speciesId: 147, baits: ["jig","live bait","trolling lure","fly"], notes: "California yellowtail are strong fighters. Iron jigs are the classic method."),
        // Japanese
        BaitEntry(speciesId: 148, baits: ["jig","live bait","trolling lure"], notes: "Japanese amberjack are revered game fish. Jigging is the primary method."),
        BaitEntry(speciesId: 149, baits: ["small jig","live shrimp","soft plastic","tenya rig"], notes: "Red sea bream are Japan's most prized fish. Tenya rigs with shrimp."),
        BaitEntry(speciesId: 150, baits: ["soft plastic","plug","fly","live bait"], notes: "Japanese sea bass are targeted with lures in estuaries and harbors."),
        BaitEntry(speciesId: 151, baits: ["live bait","jig","soft plastic","cut bait"], notes: "Olive flounder are prized sashimi fish. Fish on sandy bottom."),
        // More Freshwater
        BaitEntry(speciesId: 152, baits: ["worm","cricket","small jig","bread"], notes: "Green sunfish are aggressive and easy to catch on ultralight."),
        BaitEntry(speciesId: 153, baits: ["small crayfish","worm","small jig","spinner"], notes: "Rock bass love crayfish. Fish rocky areas with natural bait."),
        BaitEntry(speciesId: 154, baits: ["worm","cricket","small fly","bread"], notes: "Longear sunfish are colorful and fun on light tackle."),
        BaitEntry(speciesId: 155, baits: ["bread","worm","corn","small jig"], notes: "Golden shiners are excellent bass bait. Catch with bread or corn."),
        BaitEntry(speciesId: 156, baits: ["worm","corn","small jig"], notes: "White suckers are caught on bottom rigs with worm or corn."),
        BaitEntry(speciesId: 157, baits: ["dough bait","corn","worm"], notes: "Buffalo are filter feeders. Use dough baits or corn on small hooks."),
        BaitEntry(speciesId: 158, baits: ["popper","jig","fly","live bait"], notes: "Bluefin trevally are aggressive reef hunters. Cast poppers at reef edges."),
        BaitEntry(speciesId: 159, baits: ["live bait","soft plastic","jig","plug"], notes: "Mangrove jack hit hard and head for snags. Use strong line and heavy drag."),
        BaitEntry(speciesId: 160, baits: ["live bait","jig","soft plastic"], notes: "Orange-spotted grouper live around coastal reefs and estuaries."),
        BaitEntry(speciesId: 161, baits: ["soft plastic","jig","live bait","hard body lure"], notes: "Dusky flathead lie in ambush on sandy flats. Bounce soft plastics slowly."),
        BaitEntry(speciesId: 162, baits: ["metal jig","pilchard","soft plastic","fly"], notes: "Australian salmon school in large numbers. Cast metals into feeding schools."),
        BaitEntry(speciesId: 163, baits: ["jig","soft plastic","live bait","pilchard"], notes: "Silver trevally school near reefs. Light tackle with small jigs."),
        BaitEntry(speciesId: 164, baits: ["worm","prawn","bread","small soft plastic"], notes: "Black bream are estuary fish. Fish with bait on light tackle."),
        BaitEntry(speciesId: 165, baits: ["jig","minnow","worm","small spoon"], notes: "Lake whitefish feed on insects and small crustaceans. Jig through ice."),
        BaitEntry(speciesId: 166, baits: ["jig","minnow","cut bait","nightcrawler"], notes: "Burbot are cold-water predators. Jig on the bottom at night."),
        BaitEntry(speciesId: 167, baits: ["small jig","minnow","worm"], notes: "Rainbow smelt are caught through ice with tiny jigs and minnow."),
        BaitEntry(speciesId: 168, baits: ["jig","cut bait","live bait"], notes: "Hapuku are deep reef dwellers. Heavy jigs in deep water."),
        BaitEntry(speciesId: 169, baits: ["plastic worm","swimbait","topwater frog","jig","spinnerbait"], notes: "Florida bass love heavy cover. Flip and pitch into vegetation."),
        BaitEntry(speciesId: 170, baits: ["worm","jig","cricket","small crayfish"], notes: "Warmouth are aggressive panfish. Fish thick cover with worms."),
        BaitEntry(speciesId: 171, baits: ["bread","corn","maggot","small fly"], notes: "Rudd feed on the surface. Use bread crust or small dry flies."),
        BaitEntry(speciesId: 172, baits: ["maggot","worm","bread","small fly"], notes: "European minnows are tiny but great on micro tackle."),
        BaitEntry(speciesId: 173, baits: ["worm","dead bait","bread","small live fish"], notes: "Eels feed at night. Fish with worm on the bottom after dark."),
        BaitEntry(speciesId: 174, baits: ["maggot","worm","small jig"], notes: "Ruffe are small bottom feeders. Caught incidentally when perch fishing."),
        BaitEntry(speciesId: 175, baits: ["bread","corn","dough bait","cherry tomato"], notes: "Grass carp eat vegetation. Floating bread or canned corn are effective."),
        BaitEntry(speciesId: 176, baits: ["plankton mix","dough bait"], notes: "Silver carp are filter feeders. Rarely caught on hook and line intentionally."),
        BaitEntry(speciesId: 177, baits: ["plankton mix","dough bait"], notes: "Bighead carp are filter feeders. Snagged or bowfished more than hook-caught."),
        BaitEntry(speciesId: 178, baits: ["bread","corn","worm","dough bait"], notes: "Goldfish in the wild grow large. Catch with bread or corn on small hooks."),
        BaitEntry(speciesId: 179, baits: ["fruit","dough bait","worm","small jig"], notes: "Pacu eat fruit. Use pieces of fruit or dough bait."),
        BaitEntry(speciesId: 180, baits: ["live bait","cut bait","topwater","soft plastic"], notes: "Trahira are ambush predators. Use lures or live bait in slow water."),
        BaitEntry(speciesId: 181, baits: ["corn","dough bait","worm"], notes: "Prochilodus are bottom feeders during migrations. Use corn or dough."),
        BaitEntry(speciesId: 182, baits: ["spinner","live bait","fly","fruit"], notes: "Piracanjuba are omnivorous river fish. Use variety of baits."),
        BaitEntry(speciesId: 183, baits: ["jig","cut bait","squid","shrimp"], notes: "Blackspot seabream are deep-water fish. Bottom rig over rough ground."),
        BaitEntry(speciesId: 184, baits: ["jig","cut bait","pilchard","squid"], notes: "European hake are deep-water predators. Fish at night on the bottom."),
        BaitEntry(speciesId: 185, baits: ["mackerel fillet","squid","cuttlefish","large bait"], notes: "Conger eels grow huge. Fish at night near wrecks with large baits."),
        BaitEntry(speciesId: 186, baits: ["live bait","strip bait","jig"], notes: "John dory are ambush hunters. Slow trolling or drifting with live bait."),
        BaitEntry(speciesId: 187, baits: ["ragworm","shrimp","small strip bait"], notes: "Red mullet dig in sand for food. Bottom fish with worm baits."),
        BaitEntry(speciesId: 188, baits: ["feathered jig","small spinner","strip bait"], notes: "Horse mackerel school mid-water. Use strings of feathered jigs."),
        BaitEntry(speciesId: 189, baits: ["feathered jig","spinner","strip bait","fly"], notes: "Atlantic mackerel are fun on ultralight. Use small shiny lures."),
        BaitEntry(speciesId: 190, baits: ["sabiki rig","small jig","bread"], notes: "Pilchards are usually caught as bait with sabiki rigs."),
        BaitEntry(speciesId: 191, baits: ["sabiki rig","small jig"], notes: "Sprat are caught as bait in large numbers with sabiki rigs."),
        BaitEntry(speciesId: 192, baits: ["strip bait","small spinner","fly"], notes: "Garfish are surface feeders. Use floating baits or small spinners."),
        BaitEntry(speciesId: 193, baits: ["cut bait","squid","mackerel strip"], notes: "Spiny dogfish are common bycatch. Bottom fish with cut bait."),
        BaitEntry(speciesId: 194, baits: ["cut bait","squid","crab","fish strip"], notes: "Smooth-hound sharks are good sport on light tackle. Fish on the bottom."),
    ]
}
