// Auto-generated waterbody seed data — do not edit manually
import Foundation

enum WaterbodySeedData {
    static let json = Data("""
[
{"id":1,"name":"Lake Erie","type":"lake","latitude":42.2,"longitude":-81.2,"geohash":"dpnk","maxDepthM":64,"surfaceAreaKm2":25744,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"muddy\\",\\"reef\\"]","description":"Shallowest and warmest Great Lake. World-class walleye and smallmouth bass fishery. Western basin is famously productive.","fishSpeciesIds":"[8,2,10,11,1,13]","averageDepthM":19,"elevation":174},
{"id":2,"name":"Lake Michigan","type":"lake","latitude":43.8,"longitude":-87.0,"geohash":"dp4t","maxDepthM":281,"surfaceAreaKm2":57800,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"reef\\",\\"submerged_timber\\"]","description":"Third-largest Great Lake. Outstanding salmon and trout trolling. Smallmouth bass along rocky shorelines.","fishSpeciesIds":"[21,22,2,17,20,10,8]","averageDepthM":85,"elevation":176},
{"id":3,"name":"Lake Okeechobee","type":"lake","latitude":26.95,"longitude":-80.8,"geohash":"dhxp","maxDepthM":3.7,"surfaceAreaKm2":1715,"globathyId":null,"isPublic":true,"structureTypes":"[\\"weedy\\",\\"muddy\\",\\"sandy\\"]","description":"Florida's inland sea. Top-tier largemouth bass destination. Massive vegetation mats create incredible cover.","fishSpeciesIds":"[1,6,13,14]","averageDepthM":2.7,"elevation":4},
{"id":4,"name":"Table Rock Lake","type":"dam","latitude":36.6,"longitude":-93.3,"geohash":"9yqu","maxDepthM":67,"surfaceAreaKm2":170,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"submerged_timber\\",\\"sandy\\"]","description":"Ozark reservoir known for clear water bass fishing. Deep structure holds spotted and largemouth bass year-round.","fishSpeciesIds":"[1,3,2,8,4,13]","averageDepthM":24,"elevation":280},
{"id":5,"name":"Sam Rayburn Reservoir","type":"dam","latitude":31.1,"longitude":-94.1,"geohash":"9vmr","maxDepthM":24,"surfaceAreaKm2":461,"globathyId":null,"isPublic":true,"structureTypes":"[\\"submerged_timber\\",\\"weedy\\",\\"muddy\\",\\"sandy\\"]","description":"Largest lake entirely within Texas. Heavy timber provides incredible bass habitat. Excellent crappie fishing.","fishSpeciesIds":"[1,4,5,13,6]","averageDepthM":8,"elevation":50},
{"id":6,"name":"Toledo Bend Reservoir","type":"dam","latitude":31.2,"longitude":-93.6,"geohash":"9vmx","maxDepthM":33,"surfaceAreaKm2":749,"globathyId":null,"isPublic":true,"structureTypes":"[\\"submerged_timber\\",\\"weedy\\",\\"rocky\\",\\"muddy\\"]","description":"Straddles Texas-Louisiana border. Legendary largemouth bass fishery with standing timber and lily pads.","fishSpeciesIds":"[1,4,5,13,6,14]","averageDepthM":7,"elevation":52},
{"id":7,"name":"Falcon Lake","type":"dam","latitude":26.6,"longitude":-99.2,"geohash":"9mus","maxDepthM":33,"surfaceAreaKm2":333,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"submerged_timber\\"]","description":"US-Mexico border reservoir. Famous for trophy largemouth bass. Clear water with abundant rocky structure.","fishSpeciesIds":"[1,13,15]","averageDepthM":11,"elevation":92},
{"id":8,"name":"Lake Fork","type":"dam","latitude":32.8,"longitude":-95.6,"geohash":"9vk5","maxDepthM":21,"surfaceAreaKm2":108,"globathyId":null,"isPublic":true,"structureTypes":"[\\"submerged_timber\\",\\"weedy\\",\\"rocky\\"]","description":"Texas trophy bass factory. Holds multiple state records. Standing timber and hydrilla beds throughout.","fishSpeciesIds":"[1,4,5,13,6]","averageDepthM":6,"elevation":124},
{"id":9,"name":"Kentucky Lake","type":"dam","latitude":36.6,"longitude":-88.0,"geohash":"dn75","maxDepthM":23,"surfaceAreaKm2":649,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"muddy\\",\\"submerged_timber\\"]","description":"Largest artificial lake east of the Mississippi. World-class crappie and bass fishing. Extensive ledge systems.","fishSpeciesIds":"[1,2,4,5,8,13,6]","averageDepthM":5.5,"elevation":110},
{"id":10,"name":"Lake Guntersville","type":"dam","latitude":34.4,"longitude":-86.3,"geohash":"dn4v","maxDepthM":18,"surfaceAreaKm2":275,"globathyId":null,"isPublic":true,"structureTypes":"[\\"weedy\\",\\"rocky\\",\\"submerged_timber\\",\\"muddy\\"]","description":"Alabama's most popular bass lake. Massive grass beds create world-class largemouth habitat. B.A.S.S. tournament staple.","fishSpeciesIds":"[1,4,5,13,6,3]","averageDepthM":5,"elevation":181},
{"id":11,"name":"Vaal Dam","type":"dam","latitude":-26.87,"longitude":28.12,"geohash":"ke5t","maxDepthM":40,"surfaceAreaKm2":323,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"muddy\\",\\"sandy\\",\\"submerged_timber\\"]","description":"Major South African reservoir on the Vaal River. Excellent carp, yellowfish and largemouth bass. Popular weekend destination from Johannesburg.","fishSpeciesIds":"[1,13]","averageDepthM":13,"elevation":1485},
{"id":12,"name":"Hartbeespoort Dam","type":"dam","latitude":-25.75,"longitude":27.87,"geohash":"ke7q","maxDepthM":45,"surfaceAreaKm2":20,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"weedy\\",\\"muddy\\"]","description":"North West province dam near Pretoria. Bass, carp and tilapia. Scenic Magaliesberg mountain setting. Can be eutrophic in summer.","fishSpeciesIds":"[1,13]","averageDepthM":9.6,"elevation":1162},
{"id":13,"name":"Bloemhof Dam","type":"dam","latitude":-27.65,"longitude":25.62,"geohash":"ke0q","maxDepthM":21,"surfaceAreaKm2":231,"globathyId":null,"isPublic":true,"structureTypes":"[\\"muddy\\",\\"sandy\\",\\"rocky\\"]","description":"Large dam on the Vaal River in Free State. Excellent yellowfish runs. Known for big carp and mudfish.","fishSpeciesIds":"[1,13]","averageDepthM":6,"elevation":1230},
{"id":14,"name":"Sterkfontein Dam","type":"dam","latitude":-28.45,"longitude":29.05,"geohash":"ke3h","maxDepthM":92,"surfaceAreaKm2":70,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\"]","description":"High-altitude dam in the Drakensberg. Cold, deep water supports trout. Beautiful mountain scenery.","fishSpeciesIds":"[17,18]","averageDepthM":33,"elevation":1665},
{"id":15,"name":"Inanda Dam","type":"dam","latitude":-29.7,"longitude":30.87,"geohash":"ke1d","maxDepthM":47,"surfaceAreaKm2":14,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"muddy\\",\\"submerged_timber\\"]","description":"KwaZulu-Natal dam near Durban. Bass and tilapia fishing. Steep banks with drowned timber.","fishSpeciesIds":"[1,13]","averageDepthM":18,"elevation":218},
{"id":16,"name":"Lake Geneva","type":"lake","latitude":46.45,"longitude":6.5,"geohash":"u0k9","maxDepthM":310,"surfaceAreaKm2":582,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"muddy\\"]","description":"Largest lake in Western Europe. Alpine setting with perch, pike, char and trout. Famous for deep-water trolling.","fishSpeciesIds":"[11,10,17,18]","averageDepthM":154,"elevation":372},
{"id":17,"name":"Loch Lomond","type":"lake","latitude":56.08,"longitude":-4.58,"geohash":"gcpv","maxDepthM":190,"surfaceAreaKm2":71,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"weedy\\"]","description":"Largest lake in Great Britain by surface area. Pike, perch, brown trout and Atlantic salmon. Stunning Scottish Highland scenery.","fishSpeciesIds":"[11,10,18]","averageDepthM":37,"elevation":8},
{"id":18,"name":"Lake Balaton","type":"lake","latitude":46.85,"longitude":17.74,"geohash":"u2mx","maxDepthM":12.2,"surfaceAreaKm2":594,"globathyId":null,"isPublic":true,"structureTypes":"[\\"weedy\\",\\"muddy\\",\\"sandy\\"]","description":"Largest lake in Central Europe. Shallow, warm water with pike, zander, carp and catfish. Hungarian fishing paradise.","fishSpeciesIds":"[11,8,13]","averageDepthM":3.3,"elevation":105},
{"id":19,"name":"Lake Eildon","type":"dam","latitude":-37.22,"longitude":145.88,"geohash":"r1rj","maxDepthM":76,"surfaceAreaKm2":138,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"submerged_timber\\",\\"sandy\\"]","description":"Victoria's premier freshwater fishery. Trophy Murray cod, golden perch and trout. Drowned timber structures throughout.","fishSpeciesIds":"[17,18,1]","averageDepthM":25,"elevation":230},
{"id":20,"name":"Blowering Dam","type":"dam","latitude":-35.42,"longitude":148.27,"geohash":"r3bn","maxDepthM":83,"surfaceAreaKm2":47,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"submerged_timber\\",\\"sandy\\"]","description":"NSW dam in the Snowy Mountains. Known for massive Murray cod and trout. Cold, clear water with abundant structure.","fishSpeciesIds":"[17,18]","averageDepthM":28,"elevation":380},
{"id":21,"name":"Lake Texoma","type":"dam","latitude":33.8,"longitude":-96.6,"geohash":"9y6p","maxDepthM":31,"surfaceAreaKm2":360,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"muddy\\"]","description":"Texas-Oklahoma border lake. One of the best striped bass fisheries in the US. Excellent catfish and bass.","fishSpeciesIds":"[1,2,13,15,4]","averageDepthM":9,"elevation":190},
{"id":22,"name":"Lake of the Ozarks","type":"dam","latitude":38.1,"longitude":-92.7,"geohash":"9yxq","maxDepthM":40,"surfaceAreaKm2":227,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"submerged_timber\\",\\"sandy\\",\\"muddy\\"]","description":"Missouri's playground. Over 1,100 miles of shoreline. Bass, crappie, and catfish paradise with dock-rich coves.","fishSpeciesIds":"[1,3,4,5,13,6]","averageDepthM":12,"elevation":201},
{"id":23,"name":"Dale Hollow Lake","type":"dam","latitude":36.55,"longitude":-85.4,"geohash":"dn80","maxDepthM":42,"surfaceAreaKm2":113,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"submerged_timber\\"]","description":"Tennessee-Kentucky border lake. World record smallmouth bass water. Ultra-clear with deep rocky structure.","fishSpeciesIds":"[2,8,1,17,4]","averageDepthM":18,"elevation":202},
{"id":24,"name":"Lake St. Clair","type":"lake","latitude":42.4,"longitude":-82.7,"geohash":"dpmr","maxDepthM":6.4,"surfaceAreaKm2":1114,"globathyId":null,"isPublic":true,"structureTypes":"[\\"weedy\\",\\"sandy\\",\\"muddy\\"]","description":"Connecting lake between Huron and Erie. World-class smallmouth and musky fishery. Extensive weed beds and flats.","fishSpeciesIds":"[2,12,8,10,11]","averageDepthM":3.4,"elevation":175},
{"id":25,"name":"Lake Champlain","type":"lake","latitude":44.5,"longitude":-73.3,"geohash":"drue","maxDepthM":122,"surfaceAreaKm2":1127,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"weedy\\",\\"muddy\\"]","description":"Vermont-New York border lake. Legendary bass tournament destination. Diverse structure supports incredible variety.","fishSpeciesIds":"[1,2,11,8,10,4,20]","averageDepthM":19.5,"elevation":30},
{"id":26,"name":"Lake Mead","type":"dam","latitude":36.15,"longitude":-114.5,"geohash":"9qqm","maxDepthM":162,"surfaceAreaKm2":640,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\"]","description":"Largest reservoir in the US by capacity. Desert lake with striped bass, largemouth, and catfish. Dramatic canyon scenery.","fishSpeciesIds":"[1,13,17]","averageDepthM":55,"elevation":372},
{"id":27,"name":"Mississippi River - Pool 4","type":"river","latitude":44.4,"longitude":-92.0,"geohash":"9zwc","maxDepthM":15,"surfaceAreaKm2":48,"globathyId":null,"isPublic":true,"structureTypes":"[\\"sandy\\",\\"muddy\\",\\"rocky\\",\\"submerged_timber\\"]","description":"One of the best walleye and sauger pools on the upper Mississippi. Wing dams and current breaks hold fish year-round.","fishSpeciesIds":"[8,9,1,2,13,15,4]","averageDepthM":4,"elevation":198},
{"id":28,"name":"Lake Biwa","type":"lake","latitude":35.25,"longitude":136.1,"geohash":"xn16","maxDepthM":103.6,"surfaceAreaKm2":670,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"weedy\\"]","description":"Japan's largest lake. Produced the world record largemouth bass (10.12 kg). Unique endemic species alongside introduced bass.","fishSpeciesIds":"[1]","averageDepthM":41,"elevation":85},
{"id":29,"name":"Ebro River Delta","type":"estuary","latitude":40.7,"longitude":0.75,"geohash":"sp5s","maxDepthM":8,"surfaceAreaKm2":32,"globathyId":null,"isPublic":true,"structureTypes":"[\\"muddy\\",\\"sandy\\",\\"weedy\\"]","description":"Spain's most famous fishing destination. Monster carp, giant wels catfish, and zander. River and delta sections offer different experiences.","fishSpeciesIds":"[13]","averageDepthM":3,"elevation":2},
{"id":30,"name":"Lake Nasser","type":"dam","latitude":22.6,"longitude":32.0,"geohash":"s9bb","maxDepthM":130,"surfaceAreaKm2":5250,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\"]","description":"Massive Egyptian reservoir behind the Aswan High Dam. World-famous for giant Nile perch and tigerfish. Remote and spectacular.","fishSpeciesIds":"[13]","averageDepthM":25,"elevation":183},
{"id":31,"name":"Lac de Sainte-Croix","type":"dam","latitude":43.76,"longitude":6.18,"geohash":"spgf","maxDepthM":90,"surfaceAreaKm2":22,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\"]","description":"Turquoise reservoir in Provence, France. Pike, perch, carp and black bass. Stunning Gorges du Verdon setting.","fishSpeciesIds":"[11,10,1]","averageDepthM":30,"elevation":477},
{"id":32,"name":"Lake Kariba","type":"dam","latitude":-16.55,"longitude":28.75,"geohash":"kdrm","maxDepthM":97,"surfaceAreaKm2":5580,"globathyId":null,"isPublic":true,"structureTypes":"[\\"submerged_timber\\",\\"rocky\\",\\"sandy\\"]","description":"Massive Zambia-Zimbabwe border reservoir. Legendary tigerfish and bream fishing among drowned forests. Safari and fishing combined.","fishSpeciesIds":"[13]","averageDepthM":29,"elevation":485},
{"id":33,"name":"Lake Taupo","type":"lake","latitude":-38.8,"longitude":176.05,"geohash":"rcfp","maxDepthM":186,"surfaceAreaKm2":616,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"volcanic\\"]","description":"New Zealand's largest lake. World-class rainbow and brown trout. Volcanic caldera with incredibly clear water.","fishSpeciesIds":"[17,18]","averageDepthM":110,"elevation":357},
{"id":34,"name":"Lake Simcoe","type":"lake","latitude":44.4,"longitude":-79.35,"geohash":"dpxe","maxDepthM":41,"surfaceAreaKm2":722,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\",\\"weedy\\",\\"muddy\\"]","description":"Ontario's premier ice fishing lake. Excellent perch, lake trout, whitefish. Popular year-round fishery near Toronto.","fishSpeciesIds":"[10,20,2,11,1]","averageDepthM":15,"elevation":219},
{"id":35,"name":"Lake Travis","type":"dam","latitude":30.4,"longitude":-97.9,"geohash":"9v6e","maxDepthM":58,"surfaceAreaKm2":77,"globathyId":null,"isPublic":true,"structureTypes":"[\\"rocky\\",\\"sandy\\"]","description":"Austin, Texas hill country lake. Largemouth and Guadalupe bass. Dramatic limestone cliffs and clear water.","fishSpeciesIds":"[1,3,13]","averageDepthM":19,"elevation":208}
]
""".utf8)
}
