#!/usr/bin/env python3
"""Generate expanded species_seed.json with 200+ global game fish."""
import json

species = [
    # === FRESHWATER - NORTH AMERICA ===
    {"id":1,"scientificName":"Micropterus salmoides","commonName":"Largemouth Bass","family":"Centrarchidae","habitat":"freshwater","minTempC":10,"maxTempC":32,"optimalTempC":21,"fishbaseId":3181},
    {"id":2,"scientificName":"Micropterus dolomieu","commonName":"Smallmouth Bass","family":"Centrarchidae","habitat":"freshwater","minTempC":8,"maxTempC":28,"optimalTempC":18,"fishbaseId":3180},
    {"id":3,"scientificName":"Micropterus punctulatus","commonName":"Spotted Bass","family":"Centrarchidae","habitat":"freshwater","minTempC":12,"maxTempC":30,"optimalTempC":22,"fishbaseId":3182},
    {"id":4,"scientificName":"Pomoxis nigromaculatus","commonName":"Black Crappie","family":"Centrarchidae","habitat":"freshwater","minTempC":8,"maxTempC":28,"optimalTempC":18,"fishbaseId":3367},
    {"id":5,"scientificName":"Pomoxis annularis","commonName":"White Crappie","family":"Centrarchidae","habitat":"freshwater","minTempC":10,"maxTempC":28,"optimalTempC":19,"fishbaseId":3366},
    {"id":6,"scientificName":"Lepomis macrochirus","commonName":"Bluegill","family":"Centrarchidae","habitat":"freshwater","minTempC":12,"maxTempC":32,"optimalTempC":24,"fishbaseId":3359},
    {"id":7,"scientificName":"Lepomis gibbosus","commonName":"Pumpkinseed","family":"Centrarchidae","habitat":"freshwater","minTempC":8,"maxTempC":28,"optimalTempC":20,"fishbaseId":3358},
    {"id":8,"scientificName":"Sander vitreus","commonName":"Walleye","family":"Percidae","habitat":"freshwater","minTempC":4,"maxTempC":24,"optimalTempC":15,"fishbaseId":3850},
    {"id":9,"scientificName":"Sander canadensis","commonName":"Sauger","family":"Percidae","habitat":"freshwater","minTempC":4,"maxTempC":22,"optimalTempC":14,"fishbaseId":3849},
    {"id":10,"scientificName":"Perca flavescens","commonName":"Yellow Perch","family":"Percidae","habitat":"freshwater","minTempC":4,"maxTempC":24,"optimalTempC":16,"fishbaseId":3852},
    {"id":11,"scientificName":"Esox lucius","commonName":"Northern Pike","family":"Esocidae","habitat":"freshwater","minTempC":4,"maxTempC":24,"optimalTempC":15,"fishbaseId":258},
    {"id":12,"scientificName":"Esox masquinongy","commonName":"Muskellunge","family":"Esocidae","habitat":"freshwater","minTempC":8,"maxTempC":26,"optimalTempC":18,"fishbaseId":259},
    {"id":13,"scientificName":"Ictalurus punctatus","commonName":"Channel Catfish","family":"Ictaluridae","habitat":"freshwater","minTempC":10,"maxTempC":32,"optimalTempC":24,"fishbaseId":2955},
    {"id":14,"scientificName":"Pylodictis olivaris","commonName":"Flathead Catfish","family":"Ictaluridae","habitat":"freshwater","minTempC":12,"maxTempC":32,"optimalTempC":26,"fishbaseId":3001},
    {"id":15,"scientificName":"Ictalurus furcatus","commonName":"Blue Catfish","family":"Ictaluridae","habitat":"freshwater","minTempC":10,"maxTempC":32,"optimalTempC":25,"fishbaseId":2954},
    {"id":16,"scientificName":"Ameiurus nebulosus","commonName":"Brown Bullhead","family":"Ictaluridae","habitat":"freshwater","minTempC":6,"maxTempC":28,"optimalTempC":20,"fishbaseId":2924},
    {"id":17,"scientificName":"Oncorhynchus mykiss","commonName":"Rainbow Trout","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":20,"optimalTempC":13,"fishbaseId":239},
    {"id":18,"scientificName":"Salmo trutta","commonName":"Brown Trout","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":22,"optimalTempC":14,"fishbaseId":238},
    {"id":19,"scientificName":"Salvelinus fontinalis","commonName":"Brook Trout","family":"Salmonidae","habitat":"freshwater","minTempC":2,"maxTempC":18,"optimalTempC":12,"fishbaseId":246},
    {"id":20,"scientificName":"Salvelinus namaycush","commonName":"Lake Trout","family":"Salmonidae","habitat":"freshwater","minTempC":2,"maxTempC":14,"optimalTempC":10,"fishbaseId":248},
    {"id":21,"scientificName":"Oncorhynchus tshawytscha","commonName":"Chinook Salmon","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":18,"optimalTempC":12,"fishbaseId":244},
    {"id":22,"scientificName":"Oncorhynchus kisutch","commonName":"Coho Salmon","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":16,"optimalTempC":11,"fishbaseId":241},
    {"id":23,"scientificName":"Oncorhynchus nerka","commonName":"Sockeye Salmon","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":16,"optimalTempC":12,"fishbaseId":242},
    {"id":24,"scientificName":"Oncorhynchus gorbuscha","commonName":"Pink Salmon","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":14,"optimalTempC":10,"fishbaseId":240},
    {"id":25,"scientificName":"Salvelinus alpinus","commonName":"Arctic Char","family":"Salmonidae","habitat":"freshwater","minTempC":1,"maxTempC":14,"optimalTempC":8,"fishbaseId":245},
    {"id":26,"scientificName":"Morone saxatilis","commonName":"Striped Bass","family":"Moronidae","habitat":"brackish","minTempC":8,"maxTempC":26,"optimalTempC":18,"fishbaseId":3379},
    {"id":27,"scientificName":"Morone chrysops","commonName":"White Bass","family":"Moronidae","habitat":"freshwater","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":3377},
    {"id":28,"scientificName":"Aplodinotus grunniens","commonName":"Freshwater Drum","family":"Sciaenidae","habitat":"freshwater","minTempC":10,"maxTempC":28,"optimalTempC":22,"fishbaseId":1673},
    {"id":29,"scientificName":"Amia calva","commonName":"Bowfin","family":"Amiidae","habitat":"freshwater","minTempC":10,"maxTempC":30,"optimalTempC":22,"fishbaseId":2556},
    {"id":30,"scientificName":"Lepisosteus osseus","commonName":"Longnose Gar","family":"Lepisosteidae","habitat":"freshwater","minTempC":12,"maxTempC":32,"optimalTempC":24,"fishbaseId":1075},
    {"id":31,"scientificName":"Atractosteus spatula","commonName":"Alligator Gar","family":"Lepisosteidae","habitat":"freshwater","minTempC":14,"maxTempC":34,"optimalTempC":26,"fishbaseId":1074},
    # === FRESHWATER - EUROPE ===
    {"id":32,"scientificName":"Sander lucioperca","commonName":"Zander","family":"Percidae","habitat":"freshwater","minTempC":4,"maxTempC":26,"optimalTempC":16,"fishbaseId":3851},
    {"id":33,"scientificName":"Silurus glanis","commonName":"Wels Catfish","family":"Siluridae","habitat":"freshwater","minTempC":6,"maxTempC":28,"optimalTempC":20,"fishbaseId":4728},
    {"id":34,"scientificName":"Cyprinus carpio","commonName":"Common Carp","family":"Cyprinidae","habitat":"freshwater","minTempC":6,"maxTempC":32,"optimalTempC":22,"fishbaseId":1450},
    {"id":35,"scientificName":"Tinca tinca","commonName":"Tench","family":"Cyprinidae","habitat":"freshwater","minTempC":6,"maxTempC":28,"optimalTempC":20,"fishbaseId":4804},
    {"id":36,"scientificName":"Rutilus rutilus","commonName":"Roach","family":"Cyprinidae","habitat":"freshwater","minTempC":4,"maxTempC":24,"optimalTempC":16,"fishbaseId":4738},
    {"id":37,"scientificName":"Abramis brama","commonName":"Common Bream","family":"Cyprinidae","habitat":"freshwater","minTempC":4,"maxTempC":26,"optimalTempC":18,"fishbaseId":255},
    {"id":38,"scientificName":"Leuciscus idus","commonName":"Ide","family":"Cyprinidae","habitat":"freshwater","minTempC":4,"maxTempC":24,"optimalTempC":16,"fishbaseId":4670},
    {"id":39,"scientificName":"Thymallus thymallus","commonName":"European Grayling","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":18,"optimalTempC":12,"fishbaseId":250},
    {"id":40,"scientificName":"Hucho hucho","commonName":"Huchen","family":"Salmonidae","habitat":"freshwater","minTempC":4,"maxTempC":16,"optimalTempC":10,"fishbaseId":236},
    {"id":41,"scientificName":"Barbus barbus","commonName":"Barbel","family":"Cyprinidae","habitat":"freshwater","minTempC":6,"maxTempC":24,"optimalTempC":16,"fishbaseId":4706},
    {"id":42,"scientificName":"Aspius aspius","commonName":"Asp","family":"Cyprinidae","habitat":"freshwater","minTempC":6,"maxTempC":26,"optimalTempC":18,"fishbaseId":4704},
    # === FRESHWATER - AFRICA ===
    {"id":43,"scientificName":"Lates niloticus","commonName":"Nile Perch","family":"Latidae","habitat":"freshwater","minTempC":20,"maxTempC":32,"optimalTempC":26,"fishbaseId":349},
    {"id":44,"scientificName":"Clarias gariepinus","commonName":"African Sharptooth Catfish","family":"Clariidae","habitat":"freshwater","minTempC":16,"maxTempC":35,"optimalTempC":28,"fishbaseId":1934},
    {"id":45,"scientificName":"Oreochromis niloticus","commonName":"Nile Tilapia","family":"Cichlidae","habitat":"freshwater","minTempC":16,"maxTempC":35,"optimalTempC":28,"fishbaseId":2},
    {"id":46,"scientificName":"Hydrocynus vittatus","commonName":"Tigerfish","family":"Alestidae","habitat":"freshwater","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":2088},
    {"id":47,"scientificName":"Micropterus salmoides","commonName":"SA Largemouth Bass","family":"Centrarchidae","habitat":"freshwater","minTempC":14,"maxTempC":30,"optimalTempC":22,"fishbaseId":3181},
    # === FRESHWATER - SOUTH AMERICA ===
    {"id":48,"scientificName":"Cichla ocellaris","commonName":"Peacock Bass","family":"Cichlidae","habitat":"freshwater","minTempC":22,"maxTempC":34,"optimalTempC":28,"fishbaseId":1880},
    {"id":49,"scientificName":"Arapaima gigas","commonName":"Arapaima","family":"Arapaimidae","habitat":"freshwater","minTempC":24,"maxTempC":32,"optimalTempC":28,"fishbaseId":2076},
    {"id":50,"scientificName":"Salminus brasiliensis","commonName":"Dorado","family":"Characidae","habitat":"freshwater","minTempC":18,"maxTempC":28,"optimalTempC":24,"fishbaseId":47233},
    # === FRESHWATER - ASIA/OCEANIA ===
    {"id":51,"scientificName":"Channa striata","commonName":"Snakehead","family":"Channidae","habitat":"freshwater","minTempC":18,"maxTempC":34,"optimalTempC":26,"fishbaseId":5765},
    {"id":52,"scientificName":"Tor putitora","commonName":"Golden Mahseer","family":"Cyprinidae","habitat":"freshwater","minTempC":10,"maxTempC":26,"optimalTempC":18,"fishbaseId":24971},
    {"id":53,"scientificName":"Maccullochella peelii","commonName":"Murray Cod","family":"Percichthyidae","habitat":"freshwater","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":12437},
    {"id":54,"scientificName":"Bidyanus bidyanus","commonName":"Silver Perch","family":"Terapontidae","habitat":"freshwater","minTempC":12,"maxTempC":30,"optimalTempC":22,"fishbaseId":12452},
    {"id":55,"scientificName":"Lates calcarifer","commonName":"Barramundi","family":"Latidae","habitat":"brackish","minTempC":20,"maxTempC":34,"optimalTempC":28,"fishbaseId":348},
    # === MARINE - INSHORE ===
    {"id":56,"scientificName":"Centropomus undecimalis","commonName":"Common Snook","family":"Centropomidae","habitat":"brackish","minTempC":18,"maxTempC":32,"optimalTempC":26,"fishbaseId":345},
    {"id":57,"scientificName":"Megalops atlanticus","commonName":"Atlantic Tarpon","family":"Megalopidae","habitat":"brackish","minTempC":22,"maxTempC":32,"optimalTempC":28,"fishbaseId":938},
    {"id":58,"scientificName":"Albula vulpes","commonName":"Bonefish","family":"Albulidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":931},
    {"id":59,"scientificName":"Sciaenops ocellatus","commonName":"Red Drum","family":"Sciaenidae","habitat":"brackish","minTempC":14,"maxTempC":30,"optimalTempC":24,"fishbaseId":425},
    {"id":60,"scientificName":"Cynoscion nebulosus","commonName":"Spotted Seatrout","family":"Sciaenidae","habitat":"brackish","minTempC":12,"maxTempC":30,"optimalTempC":22,"fishbaseId":419},
    {"id":61,"scientificName":"Paralichthys lethostigma","commonName":"Southern Flounder","family":"Paralichthyidae","habitat":"brackish","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":566},
    {"id":62,"scientificName":"Pogonias cromis","commonName":"Black Drum","family":"Sciaenidae","habitat":"brackish","minTempC":12,"maxTempC":30,"optimalTempC":22,"fishbaseId":424},
    {"id":63,"scientificName":"Rachycentron canadum","commonName":"Cobia","family":"Rachycentridae","habitat":"marine","minTempC":20,"maxTempC":32,"optimalTempC":26,"fishbaseId":1493},
    {"id":64,"scientificName":"Trachinotus falcatus","commonName":"Permit","family":"Carangidae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":1984},
    {"id":65,"scientificName":"Caranx hippos","commonName":"Crevalle Jack","family":"Carangidae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":26,"fishbaseId":1971},
    {"id":66,"scientificName":"Lutjanus campechanus","commonName":"Red Snapper","family":"Lutjanidae","habitat":"marine","minTempC":16,"maxTempC":28,"optimalTempC":22,"fishbaseId":1438},
    {"id":67,"scientificName":"Lutjanus griseus","commonName":"Mangrove Snapper","family":"Lutjanidae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":1440},
    {"id":68,"scientificName":"Epinephelus morio","commonName":"Red Grouper","family":"Serranidae","habitat":"marine","minTempC":16,"maxTempC":28,"optimalTempC":22,"fishbaseId":7860},
    {"id":69,"scientificName":"Mycteroperca microlepis","commonName":"Gag Grouper","family":"Serranidae","habitat":"marine","minTempC":16,"maxTempC":28,"optimalTempC":22,"fishbaseId":7868},
    {"id":70,"scientificName":"Epinephelus itajara","commonName":"Goliath Grouper","family":"Serranidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":7859},
    {"id":71,"scientificName":"Scomberomorus cavalla","commonName":"King Mackerel","family":"Scombridae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":115},
    {"id":72,"scientificName":"Scomberomorus maculatus","commonName":"Spanish Mackerel","family":"Scombridae","habitat":"marine","minTempC":18,"maxTempC":28,"optimalTempC":24,"fishbaseId":116},
    {"id":73,"scientificName":"Pomatomus saltatrix","commonName":"Bluefish","family":"Pomatomidae","habitat":"marine","minTempC":12,"maxTempC":28,"optimalTempC":20,"fishbaseId":503},
    {"id":74,"scientificName":"Archosargus probatocephalus","commonName":"Sheepshead","family":"Sparidae","habitat":"marine","minTempC":12,"maxTempC":28,"optimalTempC":20,"fishbaseId":1410},
    {"id":75,"scientificName":"Lagodon rhomboides","commonName":"Pinfish","family":"Sparidae","habitat":"marine","minTempC":14,"maxTempC":30,"optimalTempC":22,"fishbaseId":1413},
    # === MARINE - OFFSHORE / PELAGIC ===
    {"id":76,"scientificName":"Thunnus albacares","commonName":"Yellowfin Tuna","family":"Scombridae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":143},
    {"id":77,"scientificName":"Thunnus thynnus","commonName":"Bluefin Tuna","family":"Scombridae","habitat":"marine","minTempC":8,"maxTempC":26,"optimalTempC":18,"fishbaseId":147},
    {"id":78,"scientificName":"Thunnus alalunga","commonName":"Albacore Tuna","family":"Scombridae","habitat":"marine","minTempC":12,"maxTempC":24,"optimalTempC":18,"fishbaseId":142},
    {"id":79,"scientificName":"Katsuwonus pelamis","commonName":"Skipjack Tuna","family":"Scombridae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":109},
    {"id":80,"scientificName":"Thunnus obesus","commonName":"Bigeye Tuna","family":"Scombridae","habitat":"marine","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":144},
    {"id":81,"scientificName":"Coryphaena hippurus","commonName":"Mahi-Mahi","family":"Coryphaenidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":419},
    {"id":82,"scientificName":"Istiophorus platypterus","commonName":"Atlantic Sailfish","family":"Istiophoridae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":102},
    {"id":83,"scientificName":"Makaira nigricans","commonName":"Blue Marlin","family":"Istiophoridae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":104},
    {"id":84,"scientificName":"Tetrapturus albidus","commonName":"White Marlin","family":"Istiophoridae","habitat":"marine","minTempC":20,"maxTempC":28,"optimalTempC":24,"fishbaseId":106},
    {"id":85,"scientificName":"Xiphias gladius","commonName":"Swordfish","family":"Xiphiidae","habitat":"marine","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":107},
    {"id":86,"scientificName":"Acanthocybium solandri","commonName":"Wahoo","family":"Scombridae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":108},
    {"id":87,"scientificName":"Caranx ignobilis","commonName":"Giant Trevally","family":"Carangidae","habitat":"marine","minTempC":22,"maxTempC":32,"optimalTempC":28,"fishbaseId":1975},
    {"id":88,"scientificName":"Seriola dumerili","commonName":"Greater Amberjack","family":"Carangidae","habitat":"marine","minTempC":16,"maxTempC":28,"optimalTempC":24,"fishbaseId":1988},
    {"id":89,"scientificName":"Seriola lalandi","commonName":"Yellowtail Kingfish","family":"Carangidae","habitat":"marine","minTempC":14,"maxTempC":26,"optimalTempC":20,"fishbaseId":1990},
    {"id":90,"scientificName":"Elagatis bipinnulata","commonName":"Rainbow Runner","family":"Carangidae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":1983},
    # === MARINE - REEF / TROPICAL ===
    {"id":91,"scientificName":"Lutjanus bohar","commonName":"Two-spot Red Snapper","family":"Lutjanidae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":1437},
    {"id":92,"scientificName":"Lethrinus nebulosus","commonName":"Spangled Emperor","family":"Lethrinidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":1862},
    {"id":93,"scientificName":"Plectropomus leopardus","commonName":"Coral Trout","family":"Serranidae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":7875},
    {"id":94,"scientificName":"Epinephelus lanceolatus","commonName":"Giant Grouper","family":"Serranidae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":7858},
    {"id":95,"scientificName":"Pagrus auratus","commonName":"Australasian Snapper","family":"Sparidae","habitat":"marine","minTempC":12,"maxTempC":24,"optimalTempC":18,"fishbaseId":5815},
    # === MARINE - EUROPEAN / ATLANTIC ===
    {"id":96,"scientificName":"Dicentrarchus labrax","commonName":"European Sea Bass","family":"Moronidae","habitat":"marine","minTempC":8,"maxTempC":24,"optimalTempC":16,"fishbaseId":63},
    {"id":97,"scientificName":"Gadus morhua","commonName":"Atlantic Cod","family":"Gadidae","habitat":"marine","minTempC":2,"maxTempC":14,"optimalTempC":8,"fishbaseId":69},
    {"id":98,"scientificName":"Pollachius pollachius","commonName":"Pollack","family":"Gadidae","habitat":"marine","minTempC":6,"maxTempC":16,"optimalTempC":12,"fishbaseId":78},
    {"id":99,"scientificName":"Melanogrammus aeglefinus","commonName":"Haddock","family":"Gadidae","habitat":"marine","minTempC":2,"maxTempC":12,"optimalTempC":7,"fishbaseId":74},
    {"id":100,"scientificName":"Scophthalmus maximus","commonName":"Turbot","family":"Scophthalmidae","habitat":"marine","minTempC":6,"maxTempC":18,"optimalTempC":14,"fishbaseId":1347},
    {"id":101,"scientificName":"Salmo salar","commonName":"Atlantic Salmon","family":"Salmonidae","habitat":"brackish","minTempC":4,"maxTempC":18,"optimalTempC":12,"fishbaseId":233},
    {"id":102,"scientificName":"Sparus aurata","commonName":"Gilthead Seabream","family":"Sparidae","habitat":"marine","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":1164},
    {"id":103,"scientificName":"Dentex dentex","commonName":"Common Dentex","family":"Sparidae","habitat":"marine","minTempC":12,"maxTempC":26,"optimalTempC":18,"fishbaseId":1404},
    # === SHARKS (CATCH & RELEASE) ===
    {"id":104,"scientificName":"Carcharhinus leucas","commonName":"Bull Shark","family":"Carcharhinidae","habitat":"brackish","minTempC":18,"maxTempC":32,"optimalTempC":26,"fishbaseId":873},
    {"id":105,"scientificName":"Carcharhinus limbatus","commonName":"Blacktip Shark","family":"Carcharhinidae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":874},
    {"id":106,"scientificName":"Galeocerdo cuvier","commonName":"Tiger Shark","family":"Carcharhinidae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":899},
    {"id":107,"scientificName":"Carcharodon carcharias","commonName":"Great White Shark","family":"Lamnidae","habitat":"marine","minTempC":10,"maxTempC":24,"optimalTempC":18,"fishbaseId":745},
    {"id":108,"scientificName":"Isurus oxyrinchus","commonName":"Shortfin Mako","family":"Lamnidae","habitat":"marine","minTempC":14,"maxTempC":26,"optimalTempC":20,"fishbaseId":746},
    {"id":109,"scientificName":"Prionace glauca","commonName":"Blue Shark","family":"Carcharhinidae","habitat":"marine","minTempC":10,"maxTempC":24,"optimalTempC":16,"fishbaseId":888},
    {"id":110,"scientificName":"Sphyrna mokarran","commonName":"Great Hammerhead","family":"Sphyrnidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":910},
    # === RAYS / FLATFISH ===
    {"id":111,"scientificName":"Dasyatis americana","commonName":"Southern Stingray","family":"Dasyatidae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":2565},
    {"id":112,"scientificName":"Paralichthys dentatus","commonName":"Summer Flounder","family":"Paralichthyidae","habitat":"marine","minTempC":10,"maxTempC":24,"optimalTempC":18,"fishbaseId":564},
    {"id":113,"scientificName":"Hippoglossus hippoglossus","commonName":"Atlantic Halibut","family":"Pleuronectidae","habitat":"marine","minTempC":2,"maxTempC":14,"optimalTempC":8,"fishbaseId":547},
    {"id":114,"scientificName":"Hippoglossus stenolepis","commonName":"Pacific Halibut","family":"Pleuronectidae","habitat":"marine","minTempC":2,"maxTempC":12,"optimalTempC":7,"fishbaseId":548},
    # === MORE PACIFIC / INDO-PACIFIC ===
    {"id":115,"scientificName":"Scomberomorus commerson","commonName":"Narrow-barred Spanish Mackerel","family":"Scombridae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":114},
    {"id":116,"scientificName":"Sphyraena barracuda","commonName":"Great Barracuda","family":"Sphyraenidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":1155},
    {"id":117,"scientificName":"Caranx sexfasciatus","commonName":"Bigeye Trevally","family":"Carangidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":1977},
    {"id":118,"scientificName":"Gnathanodon speciosus","commonName":"Golden Trevally","family":"Carangidae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":1984},
    {"id":119,"scientificName":"Chanos chanos","commonName":"Milkfish","family":"Chanidae","habitat":"brackish","minTempC":20,"maxTempC":34,"optimalTempC":28,"fishbaseId":80},
    {"id":120,"scientificName":"Elops saurus","commonName":"Ladyfish","family":"Elopidae","habitat":"brackish","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":936},
    # === SOUTH AFRICA SPECIFIC ===
    {"id":121,"scientificName":"Argyrosomus japonicus","commonName":"Dusky Kob","family":"Sciaenidae","habitat":"marine","minTempC":14,"maxTempC":26,"optimalTempC":20,"fishbaseId":12693},
    {"id":122,"scientificName":"Lichia amia","commonName":"Leervis (Garrick)","family":"Carangidae","habitat":"marine","minTempC":14,"maxTempC":26,"optimalTempC":20,"fishbaseId":1985},
    {"id":123,"scientificName":"Pomatomus saltatrix","commonName":"Shad (Elf)","family":"Pomatomidae","habitat":"marine","minTempC":14,"maxTempC":24,"optimalTempC":18,"fishbaseId":503},
    {"id":124,"scientificName":"Seriola lalandi","commonName":"Yellowtail (SA)","family":"Carangidae","habitat":"marine","minTempC":14,"maxTempC":24,"optimalTempC":18,"fishbaseId":1990},
    {"id":125,"scientificName":"Coracinus capensis","commonName":"Galjoen","family":"Dichistiidae","habitat":"marine","minTempC":12,"maxTempC":22,"optimalTempC":16,"fishbaseId":12345},
    {"id":126,"scientificName":"Chrysoblephus laticeps","commonName":"Red Roman","family":"Sparidae","habitat":"marine","minTempC":12,"maxTempC":22,"optimalTempC":16,"fishbaseId":5794},
    {"id":127,"scientificName":"Diplodus sargus capensis","commonName":"Blacktail","family":"Sparidae","habitat":"marine","minTempC":12,"maxTempC":24,"optimalTempC":18,"fishbaseId":1407},
    {"id":128,"scientificName":"Sarpa salpa","commonName":"Strepie","family":"Sparidae","habitat":"marine","minTempC":14,"maxTempC":24,"optimalTempC":18,"fishbaseId":1173},
    {"id":129,"scientificName":"Rhabdosargus holubi","commonName":"Cape Stumpnose","family":"Sparidae","habitat":"brackish","minTempC":14,"maxTempC":26,"optimalTempC":20,"fishbaseId":5825},
    {"id":130,"scientificName":"Lithognathus lithognathus","commonName":"White Steenbras","family":"Sparidae","habitat":"marine","minTempC":12,"maxTempC":22,"optimalTempC":16,"fishbaseId":5806},
    {"id":131,"scientificName":"Petrus rupestris","commonName":"Red Steenbras","family":"Sparidae","habitat":"marine","minTempC":14,"maxTempC":24,"optimalTempC":18,"fishbaseId":5819},
    {"id":132,"scientificName":"Polysteganus undulosus","commonName":"Seventy-four","family":"Sparidae","habitat":"marine","minTempC":16,"maxTempC":24,"optimalTempC":20,"fishbaseId":5823},
    {"id":133,"scientificName":"Thyrsites atun","commonName":"Snoek","family":"Gempylidae","habitat":"marine","minTempC":10,"maxTempC":20,"optimalTempC":14,"fishbaseId":101},
    {"id":134,"scientificName":"Epinephelus marginatus","commonName":"Dusky Grouper","family":"Serranidae","habitat":"marine","minTempC":14,"maxTempC":26,"optimalTempC":20,"fishbaseId":7862},
    # === MORE US / GLOBAL ===
    {"id":135,"scientificName":"Mycteroperca bonaci","commonName":"Black Grouper","family":"Serranidae","habitat":"marine","minTempC":18,"maxTempC":28,"optimalTempC":24,"fishbaseId":7867},
    {"id":136,"scientificName":"Centropristis striata","commonName":"Black Sea Bass","family":"Serranidae","habitat":"marine","minTempC":10,"maxTempC":24,"optimalTempC":18,"fishbaseId":7833},
    {"id":137,"scientificName":"Stenotomus chrysops","commonName":"Scup (Porgy)","family":"Sparidae","habitat":"marine","minTempC":8,"maxTempC":22,"optimalTempC":16,"fishbaseId":1174},
    {"id":138,"scientificName":"Tautoga onitis","commonName":"Tautog (Blackfish)","family":"Labridae","habitat":"marine","minTempC":6,"maxTempC":22,"optimalTempC":14,"fishbaseId":3791},
    {"id":139,"scientificName":"Mugil cephalus","commonName":"Flathead Mullet","family":"Mugilidae","habitat":"brackish","minTempC":10,"maxTempC":32,"optimalTempC":22,"fishbaseId":328},
    {"id":140,"scientificName":"Menticirrhus saxatilis","commonName":"Northern Kingfish","family":"Sciaenidae","habitat":"marine","minTempC":12,"maxTempC":26,"optimalTempC":20,"fishbaseId":421},
    {"id":141,"scientificName":"Leiostomus xanthurus","commonName":"Spot Croaker","family":"Sciaenidae","habitat":"marine","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":417},
    {"id":142,"scientificName":"Micropogonias undulatus","commonName":"Atlantic Croaker","family":"Sciaenidae","habitat":"marine","minTempC":10,"maxTempC":28,"optimalTempC":20,"fishbaseId":422},
    {"id":143,"scientificName":"Trachinotus carolinus","commonName":"Florida Pompano","family":"Carangidae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":1986},
    {"id":144,"scientificName":"Lobotes surinamensis","commonName":"Tripletail","family":"Lobotidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":1230},
    {"id":145,"scientificName":"Pterois volitans","commonName":"Red Lionfish","family":"Scorpaenidae","habitat":"marine","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":5195},
    # === PACIFIC NORTHWEST / WEST COAST ===
    {"id":146,"scientificName":"Sebastes mystinus","commonName":"Blue Rockfish","family":"Sebastidae","habitat":"marine","minTempC":8,"maxTempC":18,"optimalTempC":12,"fishbaseId":3978},
    {"id":147,"scientificName":"Ophiodon elongatus","commonName":"Lingcod","family":"Hexagrammidae","habitat":"marine","minTempC":4,"maxTempC":16,"optimalTempC":10,"fishbaseId":3949},
    {"id":148,"scientificName":"Anoplopoma fimbria","commonName":"Sablefish (Black Cod)","family":"Anoplopomatidae","habitat":"marine","minTempC":2,"maxTempC":12,"optimalTempC":6,"fishbaseId":222},
    {"id":149,"scientificName":"Semicossyphus pulcher","commonName":"California Sheephead","family":"Labridae","habitat":"marine","minTempC":10,"maxTempC":22,"optimalTempC":16,"fishbaseId":3794},
    {"id":150,"scientificName":"Seriola dorsalis","commonName":"California Yellowtail","family":"Carangidae","habitat":"marine","minTempC":14,"maxTempC":24,"optimalTempC":20,"fishbaseId":1989},
    # === JAPAN / EAST ASIA ===
    {"id":151,"scientificName":"Seriola quinqueradiata","commonName":"Japanese Amberjack (Buri)","family":"Carangidae","habitat":"marine","minTempC":12,"maxTempC":26,"optimalTempC":20,"fishbaseId":1991},
    {"id":152,"scientificName":"Pagrus major","commonName":"Red Sea Bream (Tai)","family":"Sparidae","habitat":"marine","minTempC":10,"maxTempC":26,"optimalTempC":18,"fishbaseId":5814},
    {"id":153,"scientificName":"Lateolabrax japonicus","commonName":"Japanese Sea Bass (Suzuki)","family":"Lateolabracidae","habitat":"brackish","minTempC":8,"maxTempC":26,"optimalTempC":18,"fishbaseId":346},
    {"id":154,"scientificName":"Paralichthys olivaceus","commonName":"Olive Flounder (Hirame)","family":"Paralichthyidae","habitat":"marine","minTempC":8,"maxTempC":24,"optimalTempC":16,"fishbaseId":565},
    # === PANFISH / MISC FRESHWATER ===
    {"id":155,"scientificName":"Lepomis cyanellus","commonName":"Green Sunfish","family":"Centrarchidae","habitat":"freshwater","minTempC":12,"maxTempC":30,"optimalTempC":24,"fishbaseId":3357},
    {"id":156,"scientificName":"Ambloplites rupestris","commonName":"Rock Bass","family":"Centrarchidae","habitat":"freshwater","minTempC":8,"maxTempC":26,"optimalTempC":18,"fishbaseId":3345},
    {"id":157,"scientificName":"Lepomis megalotis","commonName":"Longear Sunfish","family":"Centrarchidae","habitat":"freshwater","minTempC":12,"maxTempC":30,"optimalTempC":22,"fishbaseId":3360},
    {"id":158,"scientificName":"Notemigonus crysoleucas","commonName":"Golden Shiner","family":"Cyprinidae","habitat":"freshwater","minTempC":8,"maxTempC":28,"optimalTempC":20,"fishbaseId":2991},
    {"id":159,"scientificName":"Catostomus commersonii","commonName":"White Sucker","family":"Catostomidae","habitat":"freshwater","minTempC":4,"maxTempC":24,"optimalTempC":16,"fishbaseId":2892},
    {"id":160,"scientificName":"Ictiobus cyprinellus","commonName":"Bigmouth Buffalo","family":"Catostomidae","habitat":"freshwater","minTempC":10,"maxTempC":30,"optimalTempC":22,"fishbaseId":2894},
    # === MORE TROPICAL / EXOTIC ===
    {"id":161,"scientificName":"Caranx melampygus","commonName":"Bluefin Trevally","family":"Carangidae","habitat":"marine","minTempC":22,"maxTempC":30,"optimalTempC":26,"fishbaseId":1976},
    {"id":162,"scientificName":"Lutjanus argentimaculatus","commonName":"Mangrove Jack","family":"Lutjanidae","habitat":"brackish","minTempC":20,"maxTempC":32,"optimalTempC":26,"fishbaseId":1435},
    {"id":163,"scientificName":"Epinephelus coioides","commonName":"Orange-spotted Grouper","family":"Serranidae","habitat":"marine","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":7854},
    {"id":164,"scientificName":"Platycephalus fuscus","commonName":"Dusky Flathead","family":"Platycephalidae","habitat":"brackish","minTempC":14,"maxTempC":28,"optimalTempC":22,"fishbaseId":7910},
    {"id":165,"scientificName":"Arripis trutta","commonName":"Eastern Australian Salmon","family":"Arripidae","habitat":"marine","minTempC":10,"maxTempC":22,"optimalTempC":16,"fishbaseId":12453},
    {"id":166,"scientificName":"Pseudocaranx georgianus","commonName":"Silver Trevally","family":"Carangidae","habitat":"marine","minTempC":12,"maxTempC":24,"optimalTempC":18,"fishbaseId":1999},
    {"id":167,"scientificName":"Acanthopagrus butcheri","commonName":"Black Bream","family":"Sparidae","habitat":"brackish","minTempC":10,"maxTempC":26,"optimalTempC":18,"fishbaseId":5787},
    {"id":168,"scientificName":"Mugil cephalus","commonName":"Sea Mullet","family":"Mugilidae","habitat":"brackish","minTempC":12,"maxTempC":30,"optimalTempC":22,"fishbaseId":328},
    # === ICE FISHING / COLD WATER ===
    {"id":169,"scientificName":"Coregonus clupeaformis","commonName":"Lake Whitefish","family":"Salmonidae","habitat":"freshwater","minTempC":2,"maxTempC":16,"optimalTempC":10,"fishbaseId":229},
    {"id":170,"scientificName":"Lota lota","commonName":"Burbot","family":"Lotidae","habitat":"freshwater","minTempC":1,"maxTempC":14,"optimalTempC":6,"fishbaseId":71},
    {"id":171,"scientificName":"Osmerus mordax","commonName":"Rainbow Smelt","family":"Osmeridae","habitat":"freshwater","minTempC":2,"maxTempC":14,"optimalTempC":8,"fishbaseId":268},
    # === NEW ZEALAND ===
    {"id":172,"scientificName":"Argyrosomus japonicus","commonName":"Mulloway (NZ)","family":"Sciaenidae","habitat":"marine","minTempC":14,"maxTempC":24,"optimalTempC":18,"fishbaseId":12693},
    {"id":173,"scientificName":"Polyprion oxygeneios","commonName":"Hapuku","family":"Polyprionidae","habitat":"marine","minTempC":8,"maxTempC":18,"optimalTempC":14,"fishbaseId":7902},
    {"id":174,"scientificName":"Seriola lalandi","commonName":"Kingfish (NZ)","family":"Carangidae","habitat":"marine","minTempC":14,"maxTempC":24,"optimalTempC":18,"fishbaseId":1990},
    # === ADDITIONAL POPULAR SPECIES ===
    {"id":175,"scientificName":"Micropterus floridanus","commonName":"Florida Bass","family":"Centrarchidae","habitat":"freshwater","minTempC":14,"maxTempC":34,"optimalTempC":24,"fishbaseId":60583},
    {"id":176,"scientificName":"Lepomis gulosus","commonName":"Warmouth","family":"Centrarchidae","habitat":"freshwater","minTempC":12,"maxTempC":30,"optimalTempC":24,"fishbaseId":3361},
    {"id":177,"scientificName":"Scardinius erythrophthalmus","commonName":"Rudd","family":"Cyprinidae","habitat":"freshwater","minTempC":6,"maxTempC":26,"optimalTempC":18,"fishbaseId":4743},
    {"id":178,"scientificName":"Phoxinus phoxinus","commonName":"European Minnow","family":"Cyprinidae","habitat":"freshwater","minTempC":4,"maxTempC":20,"optimalTempC":14,"fishbaseId":4718},
    {"id":179,"scientificName":"Anguilla anguilla","commonName":"European Eel","family":"Anguillidae","habitat":"brackish","minTempC":4,"maxTempC":24,"optimalTempC":16,"fishbaseId":36},
    {"id":180,"scientificName":"Gymnocephalus cernua","commonName":"Ruffe","family":"Percidae","habitat":"freshwater","minTempC":4,"maxTempC":22,"optimalTempC":14,"fishbaseId":3854},
    {"id":181,"scientificName":"Ctenopharyngodon idella","commonName":"Grass Carp","family":"Cyprinidae","habitat":"freshwater","minTempC":10,"maxTempC":32,"optimalTempC":24,"fishbaseId":1449},
    {"id":182,"scientificName":"Hypophthalmichthys molitrix","commonName":"Silver Carp","family":"Cyprinidae","habitat":"freshwater","minTempC":8,"maxTempC":30,"optimalTempC":22,"fishbaseId":1451},
    {"id":183,"scientificName":"Hypophthalmichthys nobilis","commonName":"Bighead Carp","family":"Cyprinidae","habitat":"freshwater","minTempC":8,"maxTempC":30,"optimalTempC":22,"fishbaseId":1452},
    {"id":184,"scientificName":"Carassius auratus","commonName":"Goldfish","family":"Cyprinidae","habitat":"freshwater","minTempC":4,"maxTempC":30,"optimalTempC":20,"fishbaseId":1447},
    {"id":185,"scientificName":"Piaractus brachypomus","commonName":"Red-bellied Pacu","family":"Serrasalmidae","habitat":"freshwater","minTempC":22,"maxTempC":32,"optimalTempC":28,"fishbaseId":5808},
    {"id":186,"scientificName":"Hoplias malabaricus","commonName":"Trahira (Wolf Fish)","family":"Erythrinidae","habitat":"freshwater","minTempC":20,"maxTempC":32,"optimalTempC":26,"fishbaseId":2082},
    {"id":187,"scientificName":"Prochilodus lineatus","commonName":"Streaked Prochilod","family":"Prochilodontidae","habitat":"freshwater","minTempC":18,"maxTempC":30,"optimalTempC":24,"fishbaseId":10919},
    {"id":188,"scientificName":"Brycon orbignyanus","commonName":"Piracanjuba","family":"Bryconidae","habitat":"freshwater","minTempC":20,"maxTempC":30,"optimalTempC":26,"fishbaseId":47234},
    # === ADDITIONAL MARINE ===
    {"id":189,"scientificName":"Pagellus bogaraveo","commonName":"Blackspot Seabream","family":"Sparidae","habitat":"marine","minTempC":10,"maxTempC":22,"optimalTempC":16,"fishbaseId":1171},
    {"id":190,"scientificName":"Merluccius merluccius","commonName":"European Hake","family":"Merlucciidae","habitat":"marine","minTempC":6,"maxTempC":18,"optimalTempC":12,"fishbaseId":75},
    {"id":191,"scientificName":"Conger conger","commonName":"European Conger","family":"Congridae","habitat":"marine","minTempC":8,"maxTempC":22,"optimalTempC":14,"fishbaseId":48},
    {"id":192,"scientificName":"Zeus faber","commonName":"John Dory","family":"Zeidae","habitat":"marine","minTempC":8,"maxTempC":20,"optimalTempC":14,"fishbaseId":1001},
    {"id":193,"scientificName":"Mullus surmuletus","commonName":"Striped Red Mullet","family":"Mullidae","habitat":"marine","minTempC":10,"maxTempC":24,"optimalTempC":16,"fishbaseId":1355},
    {"id":194,"scientificName":"Trachurus trachurus","commonName":"Atlantic Horse Mackerel","family":"Carangidae","habitat":"marine","minTempC":8,"maxTempC":22,"optimalTempC":14,"fishbaseId":1993},
    {"id":195,"scientificName":"Scomber scombrus","commonName":"Atlantic Mackerel","family":"Scombridae","habitat":"marine","minTempC":6,"maxTempC":20,"optimalTempC":12,"fishbaseId":118},
    {"id":196,"scientificName":"Sardina pilchardus","commonName":"European Pilchard","family":"Clupeidae","habitat":"marine","minTempC":8,"maxTempC":22,"optimalTempC":14,"fishbaseId":1351},
    {"id":197,"scientificName":"Sprattus sprattus","commonName":"European Sprat","family":"Clupeidae","habitat":"marine","minTempC":4,"maxTempC":18,"optimalTempC":10,"fishbaseId":1358},
    {"id":198,"scientificName":"Belone belone","commonName":"Garfish","family":"Belonidae","habitat":"marine","minTempC":8,"maxTempC":22,"optimalTempC":14,"fishbaseId":201},
    {"id":199,"scientificName":"Squalus acanthias","commonName":"Spiny Dogfish","family":"Squalidae","habitat":"marine","minTempC":4,"maxTempC":16,"optimalTempC":10,"fishbaseId":766},
    {"id":200,"scientificName":"Mustelus mustelus","commonName":"Smooth-hound Shark","family":"Triakidae","habitat":"marine","minTempC":10,"maxTempC":24,"optimalTempC":16,"fishbaseId":857},
]

# Remove duplicate scientificNames (keep first)
seen = set()
unique = []
for s in species:
    if s["scientificName"] not in seen:
        seen.add(s["scientificName"])
        unique.append(s)

# Re-number IDs
for i, s in enumerate(unique):
    s["id"] = i + 1
    # Add null imageUrl
    s["imageUrl"] = None

print(f"Generated {len(unique)} unique species")
with open("ios/Currents/Resources/Data/species_seed.json", "w") as f:
    json.dump(unique, f, indent=2)
print("Written to ios/Currents/Resources/Data/species_seed.json")
